apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-webapp-staging
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: nginx-webapp
    environment: staging
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/sanjugm/helm.git
    targetRevision: HEAD
    path: helm-chart/nginx-webapp
    helm:
      valueFiles:
        - ../../k8s/environments/staging/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
