apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: nginx-webapp
  namespace: argocd
spec:
  description: Nginx Web Application Project
  sourceRepos:
    - https://github.com/sanjugm/helm.git
  destinations:
    - namespace: dev
      server: https://kubernetes.default.svc
    - namespace: staging
      server: https://kubernetes.default.svc
    - namespace: prod
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  namespaceResourceWhitelist:
    - group: ""
      kind: "*"
    - group: apps
      kind: "*"
    - group: networking.k8s.io
      kind: "*"
    - group: autoscaling
      kind: "*"
